# Generated by Django 6.0.3 on 2026-04-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='only fill this if product is on sale', max_digits=10, null=True),
        ),
    ]
