# Generated by Django 6.0.3 on 2026-04-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productdescriptionsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('column_one_content', models.TextField()),
                ('column_two_content', models.TextField(blank=True, null=True)),
                ('column_three_content', models.TextField(blank=True, null=True)),
                ('is_full_width', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='store.product')),
            ],
        ),
    ]
