# Generated by Django 6.0.3 on 2026-04-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_is_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_image',
            field=models.ImageField(blank=True, upload_to='products/promo'),
        ),
    ]
