# Generated by Django 6.0.3 on 2026-04-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_variation_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
